### ISSUE TITLE
User group in token claims

### ISSUE THREAD

**Issue by amerlin** [Azure-Samples/ms-identity-javascript-angular-spa-aspnetcore-webapi#12]
Hi, 
is possibile retrieve user groups into token? 
In the azure portal I had add group in token configuration, but I can't see in the token. 

Thanks

**Comment by derisen** [comment]
@amerlin we are working on a sample showing how to do this, and it's almost done. You can check it out [here](https://github.com/Azure-Samples/ms-identity-javascript-angular-spa-dotnetcore-webapi-roles-groups/tree/derisen/chapter2).

Let us know if you have any questions afterwards.

**Comment by derisen** [comment]
Closing this. Let us know if you have any issues in [that sample's](https://github.com/Azure-Samples/ms-identity-javascript-angular-spa-dotnetcore-webapi-roles-groups/tree/derisen/chapter2) repo.
