### ISSUE TITLE
How to move required scope check in API project out of controller?

### ISSUE THREAD

**Issue by GFoley83** [Azure-Samples/ms-identity-javascript-angular-spa-aspnetcore-webapi#13]
Scope checking in the controller inside every method is not ideal and would not be recommended for production use. I'm hoping there's a better way to do this e.g. somewhere inside `Startup.cs`?

```c#
    public class TodoListController : ControllerBase
    {
        // The Web API will only accept tokens 1) for users, and 
        // 2) having the access_as_user scope for this API
        static readonly string[] scopeRequiredByApi = new string[] { "access_as_user" }; <--- This should be in Startup.cs

        .  .  .  .  .  .  .

        // GET: api/TodoItems
        [HttpGet]
        public async Task<ActionResult<IEnumerable<TodoItem>>> GetTodoItems()
        {
            HttpContext.VerifyUserHasAnyAcceptedScope(scopeRequiredByApi);    <--- This check should be in Startup.cs
            string owner = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            return await _context.TodoItems.Where(item => item.Owner == owner).ToListAsync();
        }
}
```

**Comment by GFoley83** [comment]
Maybe something like this (untested):

```c#
// Startup.cs
services.AddAuthorization(o =>
{
    o.AddPolicy("AccessAsUserPolicy", policy =>
    {
        // Require the basic "Access app-name" claim by default
        policy.RequireClaim(Constants.ScopeClaimType, "access_as_user");
    });
});

// TodoListController .cs

[Authorize(Policy = "AccessAsUserPolicy")]
public class TodoListController : Controller
{
     . . . . 
}
```

**Comment by TiagoBrenck** [comment]
Hi @GFoley83 you are right about the policy. That could be a solution for checking if the bearer token contains the `access_as_user` scope in a centralized way.

I would advise you to pay attention to the scope claim name in the bearer token. It could be `scp` or `http://schemas.microsoft.com/identity/claims/scope`. That will mostly depend on what token version is your client app acquiring. If you know that all the client apps for that API will have the same claim type name, then you are good to go. Otherwise, you can implement an **OR** condition. 

```c#
services.AddAuthorization(o =>
{
    o.AddPolicy("AccessAsUserPolicy", policy =>
    {
        // Require the basic "Access app-name" claim by default
        policy.RequireAssertion(context =>
        {
            bool hasScpClaim = context.User.HasClaim("scp", "access_as_user");
            bool hasV1ScopeClaim = context.User.HasClaim("http://schemas.microsoft.com/identity/claims/scope", "access_as_user");
            return hasScpClaim || hasV1ScopeClaim;
        });
    });
});
```

**Comment by GFoley83** [comment]
Thanks Tiago. I think the solution should include this way of doing things instead of the current approach but maybe mention the current approach in the README as an alternative? Better practice.

**Comment by TiagoBrenck** [comment]
@jmprieur Should we start promoting the scope validation using policy, so it can be applied globally, other than using `HttpContext.VerifyUserHasAnyAcceptedScope();` on every action result?

Thanks

**Comment by derisen** [comment]
The suggestion is being considered by the Identity.Web team. Closing this for now.

**Comment by GFoley83** [comment]
@derisen Closing this issue makes no sense until a conclusion has been reached? Would you mind reopening so it doesn't get lost and forgotten about?

**Comment by derisen** [comment]
Not at all, but I think a better place to post this issue would be [Microsoft.Identity.Web](https://github.com/AzureAD/microsoft-identity-web) repo.

**Comment by derisen** [comment]
@GFoley83 just to give you an update: your request is in the backlog however it has low priority. The team has a preference for a more granular approach (also [related ](https://github.com/AzureAD/microsoft-identity-web/wiki/Managing-incremental-consent-and-conditional-access#in-mvc-controllers)). We won't be updating the sample before that. Closing this now as no further action to take here. Please open a new issue in [Microsoft.Identity.Web](https://github.com/AzureAD/microsoft-identity-web) repo for tracking.
