### ISSUE TITLE
FHIR API - Invalid token and audience is invalid

### ISSUE THREAD

**Issue by RahulKate** [Azure-Samples/ms-identity-javascript-angular-spa-aspnetcore-webapi#20]
## Library
- [ ] `@azure/msal-angular@1.0.0`
- [ ] `msal": "^1.3.2`

## Framework
Angular SPA

## Description
Trying to access FHIR API using MSAL authentication, able to successfully authenticate but failed in case of authorization,,,

![image](https://user-images.githubusercontent.com/13742253/91445881-5493d600-e894-11ea-979a-3c289d8c3836.png)

## Error Message
Invalid token and audience is invalid

![image](https://user-images.githubusercontent.com/13742253/91445828-3f1eac00-e894-11ea-8178-6a2ae422921e.png)

## Security
Authorization

## Regression
Nope

## Browsers/Environment
- [ ] Chrome

**Comment by derisen** [comment]
@RahulKate would you mind providing your msal configuration and some reproduction steps? 

As a first guess, can you provide the accepted token version for your API? You can find it in your **application manifest**:	

`"accessTokenAcceptedVersion": 2,`

Audience is represented as:

- clientID of the resource (your API) in version 1.
- api//clientID in version 2

There might be a mismatch due to the version difference.

**Comment by RahulKate** [comment]
I am using Azure FHIR API which is published by Microsoft, platform as a service,
https://expresshitachi.azurehealthcareapis.com/metadata

Trying to retrieve Patient's data using below url, able to to get results from the same API using POSTMAN,
https://expresshitachi.azurehealthcareapis.com/Patient

![image](https://user-images.githubusercontent.com/13742253/91504047-a581e980-e8e9-11ea-8848-c316930c0bdc.png)


Getting authorization error while calling the API from Angular app using MSAL library, How to check the API exposed by Microsoft supports which version(accessTokenAcceptedVersion) and shall be able to call using new MSAL library....
https://expresshitachi.azurehealthcareapis.com/Patient

**Comment by RahulKate** [comment]
Issue was resolved, entries in protected resource mas was not proper, it should be below format for FHIR API,

![image](https://user-images.githubusercontent.com/13742253/91548013-62a03000-e942-11ea-8ac4-81367912237d.png)
