### ISSUE TITLE
The Frame attempting navigation of the top level window is sandboxed, but the flag of 'allow-top-navigation' or 'allow-top-navigation-by-user-activation' is not set.

### ISSUE THREAD

**Issue by RahulKate** [Azure-Samples/ms-identity-javascript-angular-spa-aspnetcore-webapi#22]
## Library
- [ ] `@azure/msal-angular@1.0.0`
- [ ] `msal": "^1.3.2`

## Framework
Angular SPA

## Description
Trying to access FHIR API using MSAL authentication, able to successfully authenticate but failed in redirection,,,

![image](https://user-images.githubusercontent.com/13742253/91548292-ce829880-e942-11ea-8f41-ee2b6e36aa01.png)

I went through [1199](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1199) but still not able to resolve in angular....

However it is working for sample application given with todolist, Error occurred while trying to call another API from ToDoListSPA,,,,

![image](https://user-images.githubusercontent.com/13742253/91549489-a6943480-e944-11ea-817d-aa9481abaa55.png)

## Error Message
The Frame attempting navigation of the top level window is sandboxed, but the flag of 'allow-top-navigation' or 'allow-top-navigation-by-user-activation' is not set.

## Security
Authorization

## Regression
Nope

## Browsers/Environment
- [ ] Chrome

**Comment by derisen** [comment]
@RahulKate sorry for the delay. Would you mind sharing your configuration and any other details about how to reproduce this? Also your network trace would be helpful here.

**Comment by RahulKate** [comment]
Issue was resolved and it was related to defining a scope...

**Comment by rugglcon** [comment]
@RahulKate can you explain what your solution was? We are having this same problem and are setting scopes on our access token requests.
