### ISSUE TITLE
Issue running NPM start on SPA

### ISSUE THREAD

**Issue by Maraud3r** [Azure-Samples/ms-identity-javascript-angular-spa-aspnetcore-webapi#29]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
@azure/msal-angular@2.0.0-alpha.3

## Description

I have walked through the steps outlined in the documentation.
https://github.com/Azure-Samples/ms-identity-javascript-angular-spa-aspnetcore-webapi

I have created the WebAPI App Registration
I have created the SPA App Registration

I have updated the WebAPI project with all of the necessary client id / tenant id's
I have updated the auth-config.json file in the SPA with all of the necessary client id / tenant id's

When I try and run the SPA using npm start. 

I get the following error message:

Error: src/app/app.component.ts:50:37 - error TS2345: Argument of type '{ prompt?: string | undefined; state?: string | undefined; authority?: string | undefined; correlationId?: string |
undefined; claims?: string | undefined; resourceRequestMethod?: string | undefined; ... 10 more ...; scopes?: string[] | undefined; } | { ...; }' is not assignable to parameter of type 'PopupRequest | undefined'.

Please advise

**Comment by derisen** [comment]
@Maraud3r looks like the error occurs with the latest @azure/msal-angular@2.0.0-alpha.3. I've made a [PR here](https://github.com/Azure-Samples/ms-identity-javascript-angular-spa-aspnetcore-webapi/pull/30) to fix it, please take a look.
