### ISSUE TITLE
Protected Resource Map

### ISSUE THREAD

**Issue by Maraud3r** [Azure-Samples/ms-identity-javascript-angular-spa-aspnetcore-webapi#31]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library

@azure/msal-angular@2.0.0-alpha.3

## Description

How do I correctly specify resources in the protected resource map for a custom web api?

I have mine specified and the MSAL_Interceptor does not appear to be adding the "Authorization" header and the access token to the http request.

I have a endpoint that looks like this: https://someserver.xyz.com/api/GetSomeStuff

I created an App registration for the WebAPI and setup an access scope called access_as_user and specified that it was available to admins and users.

In my custom web api, I specified the client id of the app registration.

In my angular code, I changed the auth-config.json file to look like this
{
    "credentials": {
      "clientId": "617a6feb-386a-4395-8059-880e430e3329",
      "tenantId": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
    },
    "configuration": {
      "redirectUri": "http://localhost:4200",
      "postLogoutRedirectUri": "http://localhost:4200"
    },
    "resources": {
      "API": {
        "resourceUri": " https://someserver.xyz.com/api/GetSomeStuff",
        "resourceScopes": [ "api://ca026bc3-0e37-4526-8ddd-8eea8b64b09b/access_as_user" ]
      },
      "graph": {
        "resourceUri": "https://graph.microsoft.com/v1.0/me",
        "resourceScopes": ["user.read"]
      }
    }     
}

Now in my app.module.ts file my MSALInterceptorConfigFactory method looks like this
export function MSALInterceptorConfigFactory(): MsalInterceptorConfiguration {
  const protectedResourceMap = new Map<string, Array<string>>();
  protectedResourceMap.set(auth.resources.API.resourceUri, auth.resources.API.resourceScopes);
  protectedResourceMap.set(auth.resources.graph.resourceUri, auth.resources.graph.resourceScopes);
 
  return {
    interactionType: InteractionType.Redirect,
    protectedResourceMap
  };
}

Does anybody see anything wrong with what I've done?

**Comment by derisen** [comment]
@Maraud3r your configuration seems ok. Any particular error messages? Also, did you modify the `app-routing.module.ts` as to activate `MsalGuard` in the route you need the tokens?

**Comment by Maraud3r** [comment]
@derisen 
Looks like my problem was because I didn't have the MsalGuard on the route.

I have a working example now.

Thanks for your assistance.
