### ISSUE TITLE
Two AzureAD App Registrations?

### ISSUE THREAD

**Issue by Asim-A** [Azure-Samples/ms-identity-javascript-angular-spa-aspnetcore-webapi#32]
## Library

- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [x] `@azure/msal-angular@2.x.x`

## Description
This question is in regards to the readme file under the master branch (as of 12th feb. 2021). Under the [Registration](https://github.com/Azure-Samples/ms-identity-javascript-angular-spa-aspnetcore-webapi#registration) section two apps are registered to Azure Active Directory. Is this necessary? Can you not use the same client-id for the webapi and the spa?

**Comment by derisen** [comment]
@Asim-A It is technically possible, although in general it's not recommended (there are some exceptions). The main reason why it's not recommended is that separate app registrations allow you to assert more finer degree of control over your apps. I've previously answered a similar question [here](https://stackoverflow.com/a/63404450/6176452) if you would like to take look. Let me know if you need further help.

**Comment by Asim-A** [comment]
Okay. Thank you Doğan 👍

**Comment by anshul-northout** [comment]
Hi Derisen,

I used the same SPA code from GIT and created another new ASP .NET core web API. I followed all the steps carefully for Azure, SPA configuration and API configuration. I had CORS errors every time. I allowed CORS in applications and used headers in API calls. Is there any other setting I need to do in order to use the application and call the APIs?

Thanks

**Comment by derisen** [comment]
@anshul-northout can you please open a new issue and share app registration the details there?

Also, can you double check that you've registered your SPA as a "Single-page application"? (i.e. Azure portal > App registration > Your app> Authentication > Platforms)

**Comment by derisen** [comment]
Closing. Let us know.
