### ISSUE TITLE
ms-identity-javascript-angular-spa-aspnetcore-webapi  The request body must contain the following parameter: 'client_assertion' or 'client_secret'

### ISSUE THREAD

**Issue by megangerfen2** [Azure-Samples/ms-identity-javascript-angular-spa-aspnetcore-webapi#38]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library

- [ ] `@azure/msal-angular@2.0.0-alpha.3`   

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework
Core 3.1

## Description
Using the ms-identity-javascript-angular-spa-aspnetcore-webapi sample, went through the sign in process with Azure, but error occurring after Login 

## Error Message

login.microsoftonline.com/b02e93d3-199f-4fe5-9a80-6e5f1d2486fe/oauth2/v2.0/token:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)
home.component.ts:16 
ServerError: invalid_client: 7000218 - [2021-04-20 00:11:09Z]: AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.
Trace ID: 662f5e8c-9665-4fdb-80cd-0b5cca932301
Correlation ID: 6f5a7798-79c3-4f20-9320-2f363e5300ce
Timestamp: 2021-04-20 00:11:09Z - Correlation ID: 6f5a7798-79c3-4f20-9320-2f363e5300ce - Trace ID: 662f5e8c-9665-4fdb-80cd-0b5cca932301

## Security

- [x] Is this issue security related?  Yes

## Regression

- [ ] Did this behavior work before?  Not sure

Version:

## MSAL Configuration

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps

```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Browsers/Environment

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X ] IE
- [ ] Other (Please add browser name here)

**Comment by derisen** [comment]
@megangerfen2 can you share the your configuration? (masking client secret, if any). In particular, double check to make sure your SPA redirect URI is registered as **Single page application** on **Authentication** blade:

![screenshot](https://user-images.githubusercontent.com/13197548/115295850-1131f480-a10f-11eb-9f0a-27a195a5a6d1.png)
![screenshot](https://user-images.githubusercontent.com/13197548/115295858-13944e80-a10f-11eb-9c08-640e5c9eadec.png)

**Comment by megangerfen2** [comment]
Changing to SPA authentication works- need to update app registration scripts to use the correct one.

Thank you





________________________________

**Comment by derisen** [comment]
@megangerfen2 cheers! Closing this then.
