### ISSUE TITLE
Request an example with Vue.js and node

### ISSUE THREAD

**Issue by DarkLite1** [Azure-Samples/ms-identity-javascript-angular-spa-aspnetcore-webapi#6]
It would be great if there was an example like this with `Vue.js` and `node` as a backend. My Angular skills are not so super duper and dotnet is something I don't master. Thanks anyway for making this, it does exactly what I need but the translation takes a bit of time for me.

**Comment by derisen** [comment]
A Vue.js sample is certainly on our radar, though ETA is not clear. With respect to Node however, I'm afraid you'll have to wait more as the msal-node is currently [in development](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki#roadmap). In the meantime though, you can check out [this Node.js sample](https://github.com/Azure-Samples/active-directory-javascript-nodejs-webapi-v2) using [passport-azure-ad](https://github.com/AzureAD/passport-azure-ad), a library endorsed by Microsoft.

**Comment by DarkLite1** [comment]
Thank you for the feedback but I think you misunderstood me. The frontend handles the authentication in the SAP by using `msal`. The backend only needs to verify the access_token received to see if it's authenticated against AD. So I think that `msal` in the node backend is not needed. At least, I think this example in its dotnet part does not use `msal` there. 

Am I mixing things up? Once the user is authenticated on the frontend using `msal` we only need the backend to check if it's valid.

**Comment by derisen** [comment]
No worries : ) So each component of the app topology would need MSAL, or some other token exchange library. The sample here for instance is using MSAL.NET (or rather, Microsoft.Identity.Web which is based on MSAL.NET) on the back-end. The reason is that when the frontend app sends an access token to the backend, that token needs to be validated by the backend -for that, you would need MSAL again.

Check out this sample here

**Comment by DarkLite1** [comment]
Oh, that wasn't clear to me. I just thought that would've been possible without msal in a very simple way by checking against the resource app in Azure. Is there a workaround currently for just checking if the token is valid or not within node? As the token is generated in the frontend I was hoping such a check would be really easy.

**Comment by jmprieur** [comment]
@sDarkLite1 : the token is not generated in the fontend. It's acquired by the front end from Azure AD.
As @derisen wrote in the https://github.com/Azure-Samples/active-directory-javascript-nodejs-webapi-v2 sample, you'll see how the node.js Web api uses passport azure ad to validate the token.

**Comment by DarkLite1** [comment]
Thank you guys, appreciate the help. Security will always be a weak point for me but my app logic is not. So I appreciate all the help and pointers you gave me. I'll have a look at the example to use passport instead for the backend.  A Microsoft native library would've had my preference but this will do fine in the meantime. #stayhomestaysafe

**Comment by derisen** [comment]
@DarkLite1 cheers : ) msal-node is not production ready yet, but check out the [samples](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples) to get an idea. Closing this for now.
