### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by lockhartsoftware** [Azure-Samples/ms-identity-javascript-angular-spa-aspnetcore-webapi#9]
Excellent code and tutorial.

Authentication works!

However, I get a CORS exception in the console:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://localhost:44351/api/todolist/. (Reason: CORS request did not succeed).

Can you help me to resolve please?

**Comment by lockhartsoftware** [comment]
In startup.cs I changed:

                // builder.AllowAnyOrigin()
                //        .AllowAnyMethod()
                //        .AllowAnyHeader();

                builder.WithOrigins("http://localhost:4200")
                .AllowAnyMethod()
                .AllowAnyHeader()
                .AllowCredentials();

This had not effect.

**Comment by lockhartsoftware** [comment]
I made the following change to Startup.cs:

 services.AddCors(o => o.AddPolicy("default", builder => 
 {
   // builder.AllowAnyOrigin()
   //        .AllowAnyMethod()
   //        .AllowAnyHeader();

   builder.AllowAnyOrigin()
             .AllowAnyMethod()
             .AllowAnyHeader()
             .AllowCredentials()
             .WithOrigins("http://localhost:4200");
   }));

And this resolved the CORS issue for me.

**Comment by derisen** [comment]
Sorry for seeing this late @lockhartsoftware . Glad you solved your issue. Cheers : )

**Comment by lockhartsoftware** [comment]
> Sorry for seeing this late @lockhartsoftware . Glad you solved your issue. Cheers : )

No problem. This is an excellent step-by-step, hands-on tutorial. Are you planning to write a similar tutorial for an Azure Functions API? Or maybe you have done so already.

**Comment by derisen** [comment]
Thanks a lot. There are a few samples [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/sample-v2-code#azure-functions-as-web-apis) for Azure Functions API. They use `passport-azure-ad` library for authentication and are not very up-to-date, but once `msal-node` is [out](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki#roadmap) we will have new samples and more scenarios to cover.

**Comment by jwahr** [comment]
@lockhartsoftware @derisen According to this document, `AllowAnyOrigins` is insecure.
https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-3.1#set-the-allowed-origins

I am having the same issue. What is the correct fix?

Here is my `Startup.cs`
```
// register CORS policy
services.AddCors(options =>
{
	options.AddPolicy(name: "DefaultCorsPolicy",
		builder =>
		{
			builder.WithOrigins(
				// CorsOrigins in appsettings.json can contain more than one address separated by comma.
				Configuration["CorsOrigins"]
					.Split(",", StringSplitOptions.RemoveEmptyEntries)
					.ToArray()
			)
			.AllowAnyHeader()
			.AllowAnyMethod()
			.AllowCredentials();
		});
});
```

**Comment by lockhartsoftware** [comment]
This is a configuration to get the client app to communicate with the server app on the same development / test machine without a CORS issue. So yes, it would be insecure in production.

For production you would specify the url of the production client app. For example, if your client app is hosted at "http://example.com" then the configuration would be:

`builder.WithOrigins("http://example.com")`

**Comment by amerlin** [comment]
Hello, in my case the cors problem is to login.microsoftonline.com

This is my error: 

Access to XMLHttpRequest at 'https://login.microsoftonline.com/common/oauth2/authorize?client_id=75013c63-0871-48c4-b80d-0a661c1b66df&redirect_uri=https%3A%2F%2Flocalhost%3A44351%2Fsignin-oidc&response_type=id_token&scope=openid%20profile&response_mode=form_post&nonce=637286913194433264.NDkzNzRkMjUtN2Q3NC00MjRmLTk4NDUtMDI0YjU5NTljNTI5NmQyZjIyMDYtYTcxYS00YzQ0LThkNTYtZGNiYjk5M2I4Njcy&state=CfDJ8IJtch9kSxhMmNl20w5NclFa-nQYhKMhO9XBBLs8xTM39Nk0GfQu6UtKB6lR6zidgRe95pwr-7TK6qF_bUscpSc_qS6eagBm4hWYyQ8hDCvDXp2V7NnoSfGziWoTWiR-5kU0sCHBNdMWoebDVdc81w0LAeJVq8rrNsLmsCEtfSoDgv8_NtTkm1kQWjcPwawNTHniG_uSL2FfEIXxRjbEdKO0EE7D6LGcA9R3xyZ2CE-K2Bcamc_gGuDyIuIAs2K6Z2nNFwk61Q1R8Sh9Bb6iV5d4yp7gd9szagtuPIFVHQDMgAoSG-xnUdHs9dKZmWmS2g&x-client-SKU=ID_NETSTANDARD2_0&x-client-ver=5.5.0.0' (redirected from 'https://localhost:44351/api/todolist') from origin 'http://localhost:4200' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Thank
